In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('./data_csv/random_data.csv')
df

,index,Bed/Yellow,Bed/Blue,Bed/Green,Bed/White,Bed/Red,Bed/Brown,Bed/None,BookShelf/Yellow,BookShelf/Blue,...,Sofa/Red,Sofa/Brown,Sofa/None,Stand/Yellow,Stand/Blue,Stand/Green,Stand/White,Stand/Red,Stand/Brown,Stand/None
0,0,1,5,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
1,1,0,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
2,2,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
3,3,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
4,4,1,0,1,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN

In [6]:
df['Bed/Yellow'].value_counts()

1    4
0    1
Name: Bed/Yellow, dtype: int64